language: node_js
deploy:
  api_key:
    secure: caiz3hBJotU644WfUyPyWZPXGPbIyGNiZnRiVNRbAWEH7mY/0ZXrntxnowFT9eduPK5doFSQUsruLgTK0bvvDRn+gRSrRtjCFgadcWmUNjGUrFTA34jiBBDDIKQu29V29qqptC7Wg6jfOkOdH4fpvrDTEe8qe8EGSGZHLJ/pnpM=
  email: jffelsinger@gmail.com
  provider: npm
node_js:
  - '0.11'
  - '0.10'
env:
  - NODE_ENV=travis
before_install:
  - npm install -g gulp mocha
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'measurement' ]; then cd .. && eval "mv $currentfolder
    measurement" && cd generator-venm; fi
script: gulp test
